// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by process_manifests.py on 2025-07-09 10:11:53
// For detailed documentation see: components/system_contract/

#pragma once

namespace ModESP {

namespace Events {
    // Event name constants for compile-time checking
    constexpr const char* SENSOR_CALIBRATION_COMPLETE = "sensor.calibration_complete";
    constexpr const char* SENSOR_ERROR = "sensor.error";
    constexpr const char* SENSOR_READING_UPDATED = "sensor.reading_updated";
} // namespace Events

namespace States {
    // SharedState key constants
} // namespace States

} // namespace ModESP